# Generated by Django 5.1.3 on 2024-12-07 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tienda', '0003_cliente_otros_productos_ropa_zapatillas_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Botines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=30)),
                ('precio', models.FloatField()),
                ('talle_arg', models.IntegerField()),
                ('vendedor', models.CharField(max_length=30)),
                ('descripcion', models.TextField(null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='ropa',
            old_name='talle',
            new_name='talle_arg',
        ),
        migrations.RenameField(
            model_name='zapatillas',
            old_name='talle',
            new_name='talle_arg',
        ),
    ]
