# Generated by Django 5.1.3 on 2024-12-07 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tienda', '0004_botines_rename_talle_ropa_talle_arg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='zapatillas',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='productos/'),
        ),
    ]
