# Generated by Django 5.1.3 on 2024-12-08 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_tienda', '0006_botines_imagen_otros_productos_imagen_ropa_imagen'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cliente',
            new_name='Clientes',
        ),
        migrations.RenameModel(
            old_name='Vendedor',
            new_name='Vendedores',
        ),
    ]
