# Generated by Django 5.1.3 on 2024-12-08 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tienda', '0008_clientes_telefono_vendedores_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='telefono',
            field=models.BigIntegerField(null=True),
        ),
    ]
