# Generated by Django 5.1.3 on 2024-12-08 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tienda', '0009_alter_clientes_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendedores',
            name='telefono',
            field=models.BigIntegerField(null=True),
        ),
    ]
