# Generated by Django 5.1.3 on 2024-12-08 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tienda', '0011_remove_clientes_tipo_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.BigIntegerField()),
                ('descripcion', models.TextField()),
            ],
        ),
    ]
