# Generated by Django 5.1.3 on 2024-12-08 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tienda', '0012_contacto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='descripcion',
            field=models.TextField(null=True),
        ),
    ]
